Db-Services refactoring
qreal/wmp pull request #29
Opened 2016-09-07 09:13 UTC by TanVD

1.Add exceptions in all db-services (#129917889)
2.Add unit tests in all db-services (#127461159, #126217043, #129917843)

2016-09-15 16:02 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    * In case of exception save will be safely aborted
save operation will be safely aborted

2016-09-15 16:02 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    * TAborted will be thrown in following cases:
in the following cases

2016-09-15 16:03 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    * 1. Folder to save diagram into doesn't exist
The folder to save the diagram into doesn't exist

2016-09-15 16:05 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    //If not found diagram with specified id TNotFound will be thrown
TNotFound is thrown if the diagram with specified id is not found

2016-09-15 16:06 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    * In case of exception delete will be safely aborted
delete operation will be safely aborted

2016-09-15 16:07 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/exceptions/Aborted.java
> +public class Aborted extends Exception {
javadoc?

2016-09-15 16:07 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/exceptions/Aborted.java
> +
unnecessary empty line

2016-09-15 16:07 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/exceptions/ErrorConnection.java
> +public class ErrorConnection extends Exception {
javadoc

2016-09-15 16:07 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/robots/client/RobotServiceImpl.java
> +            } catch (TIdAlreadyDefined e) {
we'd better crash with such coding errors in development mode and show corresponding error in diagram service

2016-09-15 16:07 UTC, jzuken commented on thrift-definitions/exception/DbExceptions.thrift
> +//Used as a coding rule
why not unify the comments in all thrift declaration files?

2016-09-15 16:07 UTC, jzuken commented on thrift-definitions/diagram-database/DiagramDbService.thrift
> +    * TAborted will be thrown in following cases:
here and everywhere below

2016-09-15 16:09 UTC, jzuken commented on thrift-definitions/exception/DbExceptions.thrift
> +//Used in normal cases of excution (instead of returning null)
is this exception thrown always instead of returning null?

2016-09-15 16:09 UTC, jzuken commented on thrift-definitions/exception/DbExceptions.thrift
> +//Used in exceptional situations to informate other services and client
to inform

2016-09-15 16:09 UTC, jzuken commented on thrift-definitions/exception/DbExceptions.thrift
> +//Used in situation of connection errors.
in case of

2016-09-15 16:13 UTC, jzuken commented on thrift-definitions/robot-store-database/RobotDbService.thrift
> +* Robot foreign key dependency of owner to Users table NOT checked,
I can't really parse this comment :)

2016-09-15 16:16 UTC, jzuken requested changes

2016-09-15 17:26 UTC, TanVD commented on thrift-definitions/exception/DbExceptions.thrift
> +//Used in normal cases of excution (instead of returning null)
In search operations -- yes

2016-09-23 11:10 UTC, jzuken commented on db-services/db-diagram-service/src/test/java/com/qreal/wmp/db/diagram/test/dao/DaoDiagramComplexTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
I like Hamcrest assertions better :)

2016-09-23 11:17 UTC, jzuken commented on db-services/db-diagram-service/src/main/java/com/qreal/wmp/db/diagram/exceptions/Aborted.java
>  public class Aborted extends Exception {
I guess exceptions' names should end with 'Exception', like AbortedException

2016-09-23 11:21 UTC, jzuken commented on db-services/db-diagram-service/src/test/java/com/qreal/wmp/db/diagram/test/server/DbServiceHandlerDiagramTest.java
> +    public DiagramDbServiceHandler handler;
why public?

2016-09-23 11:22 UTC, jzuken commented on db-services/db-diagram-service/src/test/java/com/qreal/wmp/db/diagram/test/dao/DaoFolderTest.java
> +    public DiagramDao diagramDao;
and why  dao fields are public?

2016-09-23 11:26 UTC, jzuken commented on db-services/db-diagram-service/src/test/java/com/qreal/wmp/db/diagram/test/server/DbServiceHandlerDiagramTest.java
> +    public void saveDiagram_correctInput_diagramDaoCalled() throws TAborted, TIdAlreadyDefined, Aborted {
it is common practice to just use "throws Exception" in test methods

2016-09-23 11:42 UTC, jzuken requested changes

2016-09-23 11:42 UTC, jzuken commented on db-services/db-diagram-service/src/main/java/com/qreal/wmp/db/diagram/dao/DiagramDaoImpl.java
> +    public void rewriteDiagram(@NotNull Diagram diagram) throws Aborted {logger.trace("rewriteDiagram method called with parameters: diagram = {}", diagram.getName());
newline is lost somehow here

2016-09-23 11:42 UTC, jzuken commented on db-services/db-diagram-service/src/main/java/com/qreal/wmp/db/diagram/server/DiagramDbServiceHandler.java
> +    public DiagramDao getDiagramDao() {
do they really need to be public in the sake of testing?

2016-09-23 11:42 UTC, jzuken commented on db-services/db-diagram-service/src/test/java/com/qreal/wmp/db/diagram/test/dao/DaoDiagramComplexTest.java
> +        propertyNode.setName("namePropertyNode");
why don't we create some constructors to eliminate these setters calls?

2016-09-25 18:26 UTC, TanVD commented on db-services/db-diagram-service/src/main/java/com/qreal/wmp/db/diagram/server/DiagramDbServiceHandler.java
> +    public DiagramDao getDiagramDao() {
I don't see any other option (excepting moving tests for server to server package)

2016-10-12 11:24 UTC, jzuken requested changes

2016-10-12 11:24 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/controller/MainController.java
> +        User user = null;
we do model.addObject("robots", user.getRobots()); several lines below, I guess we sould handle this potential null value there

2016-10-12 11:24 UTC, jzuken commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/users/client/UserDetailsServiceImpl.java
> +        List<GrantedAuthority> authorities = buildUserAuthority(user.getRoles());
and again, if the user is null?

2016-10-12 11:24 UTC, jzuken commented on db-services/db-robot-store-service/src/main/java/com/qreal/wmp/db/robot/exceptions/translation/ExceptionTranslation.java
> +@Aspect
I guess it would be better to add a comment here describing all this aspect stuff.

2016-10-12 11:24 UTC, jzuken commented on db-services/db-user-service/src/main/java/com/qreal/wmp/db/user/dao/UserDaoImpl.java
> +                    e.printStackTrace();
just print stack trace?

2016-10-12 13:34 UTC, TanVD commented on db-services/db-user-service/src/main/java/com/qreal/wmp/db/user/dao/UserDaoImpl.java
> +                    e.printStackTrace();
Yep, this exception should be translated by ExceptionTranslation aspect and should never be caught here. I'll think about hack solution.

2016-10-12 13:35 UTC, TanVD commented on db-services/db-robot-store-service/src/main/java/com/qreal/wmp/db/robot/exceptions/translation/ExceptionTranslation.java
> +@Aspect
Ok, i'll add javadoc

2016-10-12 16:44 UTC, TanVD commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/controller/MainController.java
> +        User user = null;
i'll handle it, but in normal situation user cannot be null, cause to call this method user should be authorized

2016-10-12 16:46 UTC, TanVD commented on dashboard-service/src/main/java/com/qreal/wmp/dashboard/database/users/client/UserDetailsServiceImpl.java
> +        List<GrantedAuthority> authorities = buildUserAuthority(user.getRoles());
If user was not found, NotFound will be thrown.

2016-10-14 09:50 UTC, merged